// <auto-generated />
using System;
using ManageOrdersAPI.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ManageOrdersAPI.Migrations
{
    [DbContext(typeof(ManageOrdersDbContext))]
    partial class ManageOrdersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ManageOrdersAPI.Database.OrderModel", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CancelReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameClient")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NameExecutor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdOrder");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            IdOrder = 1,
                            DeliveryAddress = "ул. Пушкина, 5",
                            NameClient = "Иванов Иван",
                            NameExecutor = "Сидоров Петр",
                            PickupAddress = "ул. Ленина, 10",
                            PickupTime = new DateTime(2024, 11, 25, 0, 35, 41, 433, DateTimeKind.Local).AddTicks(6931),
                            Status = "Новая"
                        },
                        new
                        {
                            IdOrder = 2,
                            DeliveryAddress = "ул. Гоголя, 12",
                            NameClient = "Петров Сергей",
                            NameExecutor = "Иванов Андрей",
                            PickupAddress = "пр. Мира, 23",
                            PickupTime = new DateTime(2024, 11, 25, 1, 35, 41, 436, DateTimeKind.Local).AddTicks(5984),
                            Status = "Новая"
                        },
                        new
                        {
                            IdOrder = 3,
                            DeliveryAddress = "ул. Чехова, 8",
                            NameClient = "Смирнов Алексей",
                            NameExecutor = "Михайлов Игорь",
                            PickupAddress = "ул. Советская, 15",
                            PickupTime = new DateTime(2024, 11, 25, 2, 35, 41, 436, DateTimeKind.Local).AddTicks(6012),
                            Status = "Новая"
                        },
                        new
                        {
                            IdOrder = 4,
                            DeliveryAddress = "ул. Толстого, 20",
                            NameClient = "Алексеева Ольга",
                            NameExecutor = "Николаев Виталий",
                            PickupAddress = "ул. Кирова, 7",
                            PickupTime = new DateTime(2024, 11, 25, 3, 35, 41, 436, DateTimeKind.Local).AddTicks(6016),
                            Status = "Новая"
                        },
                        new
                        {
                            IdOrder = 5,
                            DeliveryAddress = "ул. Некрасова, 3",
                            NameClient = "Кузнецов Виктор",
                            NameExecutor = "Павлов Дмитрий",
                            PickupAddress = "ул. Бабушкина, 9",
                            PickupTime = new DateTime(2024, 11, 25, 4, 35, 41, 436, DateTimeKind.Local).AddTicks(6020),
                            Status = "Новая"
                        },
                        new
                        {
                            IdOrder = 6,
                            DeliveryAddress = "ул. Островского, 6",
                            NameClient = "Куликова Анна",
                            NameExecutor = "Егоров Максим",
                            PickupAddress = "ул. Труда, 14",
                            PickupTime = new DateTime(2024, 11, 25, 5, 35, 41, 436, DateTimeKind.Local).AddTicks(6023),
                            Status = "Новая"
                        },
                        new
                        {
                            IdOrder = 7,
                            DeliveryAddress = "ул. Пирогова, 11",
                            NameClient = "Морозов Артем",
                            NameExecutor = "Лебедев Денис",
                            PickupAddress = "ул. Зои Космодемьянской, 18",
                            PickupTime = new DateTime(2024, 11, 25, 6, 35, 41, 436, DateTimeKind.Local).AddTicks(6026),
                            Status = "Новая"
                        },
                        new
                        {
                            IdOrder = 8,
                            DeliveryAddress = "ул. Лермонтова, 13",
                            NameClient = "Фролова Татьяна",
                            NameExecutor = "Григорьев Олег",
                            PickupAddress = "ул. Победы, 22",
                            PickupTime = new DateTime(2024, 11, 25, 7, 35, 41, 436, DateTimeKind.Local).AddTicks(6030),
                            Status = "Новая"
                        },
                        new
                        {
                            IdOrder = 9,
                            DeliveryAddress = "ул. Тургенева, 2",
                            NameClient = "Воробьева Светлана",
                            NameExecutor = "Данилов Александр",
                            PickupAddress = "ул. Багратиона, 19",
                            PickupTime = new DateTime(2024, 11, 25, 8, 35, 41, 436, DateTimeKind.Local).AddTicks(6033),
                            Status = "Новая"
                        },
                        new
                        {
                            IdOrder = 10,
                            DeliveryAddress = "ул. Горького, 17",
                            NameClient = "Громов Михаил",
                            NameExecutor = "Романов Артем",
                            PickupAddress = "ул. Декабристов, 25",
                            PickupTime = new DateTime(2024, 11, 25, 9, 35, 41, 436, DateTimeKind.Local).AddTicks(6036),
                            Status = "Новая"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
